/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ehmlclowiedoqncymegi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobWxjbG93aWVkb3FuY3ltZWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NDk2MjEsImV4cCI6MjA4NjMyNTYyMX0.kF3oej6l8De6q2YpL2-N_GpahDAkwSD-XeaVGzJjPkE"